export const variants = {
  base: {
    flex: "flex",
    directions: [
      "flex-row",
      "flex-col",
      "flex-row-reverse",
      "flex-col-reverse",
      "flex-wrap",
      "flex-nowrap",
      "flex-wrap-reverse",
    ],
    shrink: ["shrink", "shrink-0"],
    grow: ["grow", "grow-0"],
    justifyContent: [
      "justify-normal",
      "justify-start",
      "justify-end",
      "justify-center",
      "justify-between",
    ],
    alignItems: [
      "items-stretch",
      "items-center",
      "items-start",
      "items-end",
      "items-baseline",
    ],
  },
  medium: {
    directions: [
      "md:flex-row",
      "md:flex-col",
      "md:flex-row-reverse",
      "md:flex-col-reverse",
      "md:flex-wrap",
      "md:flex-nowrap",
      "md:flex-wrap-reverse",
    ],
    shrink: ["md:shrink", "md:shrink-0"],
    grow: ["md:grow", "md:grow-0"],
    justifyContent: [
      "md:justify-normal",
      "md:justify-start",
      "md:justify-end",
      "md:justify-center",
      "md:justify-between",
    ],
    alignItems: [
      "md:items-stretch",
      "md:items-center",
      "md:items-start",
      "md:items-end",
      "md:items-baseline",
    ],
  },
  large: {
    directions: [
      "lg:flex-row",
      "lg:flex-col",
      "lg:flex-row-reverse",
      "lg:flex-col-reverse",
      "lg:flex-wrap",
      "lg:flex-nowrap",
      "lg:flex-wrap-reverse",
    ],
    shrink: ["lg:shrink", "lg:shrink-0"],
    grow: ["lg:grow", "lg:grow-0"],
    justifyContent: [
      "lg:justify-normal",
      "lg:justify-start",
      "lg:justify-end",
      "lg:justify-center",
      "lg:justify-between",
    ],
    alignItems: [
      "lg:items-stretch",
      "lg:items-center",
      "lg:items-start",
      "lg:items-end",
      "lg:items-baseline",
    ],
  },
};
