export const variants = {
  grid: "grid",

  base: {
    templates: {
      cols: [
        "grid-cols-none",
        "grid-cols-subgrid",
        "grid-cols-1",
        "grid-cols-2",
        "grid-cols-3",
        "grid-cols-4",
        "grid-cols-5",
        "grid-cols-6",
        "grids-cols-7",
        "grid-cols-8",
        "grid-cols-9",
        "grid-cols-10",
        "grid-cols-11",
        "grid-cols-12",
      ],
      rows: [
        "grid-rows-none",
        "grid-rows-subgrid",
        "grid-rows-1",
        "grid-rows-2",
        "grid-rows-3",
        "grid-rows-4",
        "grid-rows-5",
        "grid-rows-6",
        "grids-rows-7",
        "grid-rows-8",
        "grid-rows-9",
        "grid-rows-10",
        "grid-rows-11",
        "grid-rows-12",
      ],
    },
    col: {
      span: [
        "col-auto",
        "col-span-full",
        "col-span-1",
        "col-span-2",
        "col-span-3",
        "col-span-4",
        "col-span-5",
        "col-span-6",
        "col-span-7",
        "col-span-8",
        "col-span-9",
        "col-span-10",
        "col-span-11",
        "col-span-12",
      ],
      start: [
        "col-start-auto",
        "col-start-1",
        "col-start-2",
        "col-start-3",
        "col-start-4",
        "col-start-5",
        "col-start-6",
        "col-start-7",
        "col-start-8",
        "col-start-9",
        "col-start-10",
        "col-start-11",
        "col-start-12",
      ],
      end: [
        "col-end-auto",
        "col-end-1",
        "col-end-2",
        "col-end-3",
        "col-end-4",
        "col-end-5",
        "col-end-6",
        "col-end-7",
        "col-end-8",
        "col-end-9",
        "col-end-10",
        "col-end-11",
        "col-end-12",
      ],
      auto: [
        "auto-cols-auto",
        "auto-cols-min",
        "auto-cols-max",
        "auto-cols-fr",
      ],
    },
    row: {
      span: [
        "row-auto",
        "row-span-full",
        "row-span-1",
        "row-span-2",
        "row-span-3",
        "row-span-4",
        "row-span-5",
        "row-span-6",
        "row-span-7",
        "row-span-8",
        "row-span-9",
        "row-span-10",
        "row-span-11",
        "row-span-12",
      ],
      start: [
        "row-start-auto",
        "row-start-1",
        "row-start-2",
        "row-start-3",
        "row-start-4",
        "row-start-5",
        "row-start-6",
        "row-start-7",
        "row-start-8",
        "row-start-9",
        "row-start-10",
        "row-start-11",
        "row-start-12",
      ],
      end: [
        "row-end-auto",
        "row-end-1",
        "row-end-2",
        "row-end-3",
        "row-end-4",
        "row-end-5",
        "row-end-6",
        "row-end-7",
        "row-end-8",
        "row-end-9",
        "row-end-10",
        "row-end-11",
        "row-end-12",
      ],
      auto: [
        "auto-rows-auto",
        "auto-rows-min",
        "auto-rows-max",
        "auto-rows-fr",
      ],
    },
    flow: [
      "grid-flow-row",
      "grid-flow-col",
      "grid-flow-dense",
      "grid-flow-row-dense",
      "grid-flow-col-dense",
    ],
  },
  medium: {
    templates: {
      cols: [
        "md:grid-cols-none",
        "md:grid-cols-subgrid",
        "md:grid-cols-1",
        "md:grid-cols-2",
        "md:grid-cols-3",
        "md:grid-cols-4",
        "md:grid-cols-5",
        "md:grid-cols-6",
        "md:grids-cols-7",
        "md:grid-cols-8",
        "md:grid-cols-9",
        "md:grid-cols-10",
        "md:grid-cols-11",
        "md:grid-cols-12",
      ],
      rows: [
        "md:grid-rows-none",
        "md:grid-rows-subgrid",
        "md:grid-rows-1",
        "md:grid-rows-2",
        "md:grid-rows-3",
        "md:grid-rows-4",
        "md:grid-rows-5",
        "md:grid-rows-6",
        "md:grids-rows-7",
        "md:grid-rows-8",
        "md:grid-rows-9",
        "md:grid-rows-10",
        "md:grid-rows-11",
        "md:grid-rows-12",
      ],
    },
    col: {
      span: [
        "md:col-auto",
        "md:col-span-full",
        "md:col-span-1",
        "md:col-span-2",
        "md:col-span-3",
        "md:col-span-4",
        "md:col-span-5",
        "md:col-span-6",
        "md:col-span-7",
        "md:col-span-8",
        "md:col-span-9",
        "md:col-span-10",
        "md:col-span-11",
        "md:col-span-12",
      ],
      start: [
        "md:col-start-auto",
        "md:col-start-1",
        "md:col-start-2",
        "md:col-start-3",
        "md:col-start-4",
        "md:col-start-5",
        "md:col-start-6",
        "md:col-start-7",
        "md:col-start-8",
        "md:col-start-9",
        "md:col-start-10",
        "md:col-start-11",
        "md:col-start-12",
      ],
      end: [
        "md:col-end-auto",
        "md:col-end-1",
        "md:col-end-2",
        "md:col-end-3",
        "md:col-end-4",
        "md:col-end-5",
        "md:col-end-6",
        "md:col-end-7",
        "md:col-end-8",
        "md:col-end-9",
        "md:col-end-10",
        "md:col-end-11",
        "md:col-end-12",
      ],
      auto: [
        "md:auto-cols-auto",
        "md:auto-cols-min",
        "md:auto-cols-max",
        "md:auto-cols-fr",
      ],
    },
    row: {
      span: [
        "md:row-auto",
        "md:row-span-full",
        "md:row-span-1",
        "md:row-span-2",
        "md:row-span-3",
        "md:row-span-4",
        "md:row-span-5",
        "md:row-span-6",
        "md:row-span-7",
        "md:row-span-8",
        "md:row-span-9",
        "md:row-span-10",
        "md:row-span-11",
        "md:row-span-12",
      ],
      start: [
        "md:row-start-auto",
        "md:row-start-1",
        "md:row-start-2",
        "md:row-start-3",
        "md:row-start-4",
        "md:row-start-5",
        "md:row-start-6",
        "md:row-start-7",
        "md:row-start-8",
        "md:row-start-9",
        "md:row-start-10",
        "md:row-start-11",
        "md:row-start-12",
      ],
      end: [
        "md:row-end-auto",
        "md:row-end-1",
        "md:row-end-2",
        "md:row-end-3",
        "md:row-end-4",
        "md:row-end-5",
        "md:row-end-6",
        "md:row-end-7",
        "md:row-end-8",
        "md:row-end-9",
        "md:row-end-10",
        "md:row-end-11",
        "md:row-end-12",
      ],
      auto: [
        "md:auto-rows-auto",
        "md:auto-rows-min",
        "md:auto-rows-max",
        "md:auto-rows-fr",
      ],
    },
  },
  large: {
    templates: {
      cols: [
        "lg:grid-cols-none",
        "lg:grid-cols-subgrid",
        "lg:grid-cols-1",
        "lg:grid-cols-2",
        "lg:grid-cols-3",
        "lg:grid-cols-4",
        "lg:grid-cols-5",
        "lg:grid-cols-6",
        "lg:grids-cols-7",
        "lg:grid-cols-8",
        "lg:grid-cols-9",
        "lg:grid-cols-10",
        "lg:grid-cols-11",
        "lg:grid-cols-12",
      ],
      rows: [
        "lg:grid-rows-none",
        "lg:grid-rows-subgrid",
        "lg:grid-rows-1",
        "lg:grid-rows-2",
        "lg:grid-rows-3",
        "lg:grid-rows-4",
        "lg:grid-rows-5",
        "lg:grid-rows-6",
        "lg:grids-rows-7",
        "lg:grid-rows-8",
        "lg:grid-rows-9",
        "lg:grid-rows-10",
        "lg:grid-rows-11",
        "lg:grid-rows-12",
      ],
    },
    col: {
      span: [
        "lg:col-auto",
        "lg:col-span-full",
        "lg:col-span-1",
        "lg:col-span-2",
        "lg:col-span-3",
        "lg:col-span-4",
        "lg:col-span-5",
        "lg:col-span-6",
        "lg:col-span-7",
        "lg:col-span-8",
        "lg:col-span-9",
        "lg:col-span-10",
        "lg:col-span-11",
        "lg:col-span-12",
      ],
      start: [
        "lg:col-start-auto",
        "lg:col-start-1",
        "lg:col-start-2",
        "lg:col-start-3",
        "lg:col-start-4",
        "lg:col-start-5",
        "lg:col-start-6",
        "lg:col-start-7",
        "lg:col-start-8",
        "lg:col-start-9",
        "lg:col-start-10",
        "lg:col-start-11",
        "lg:col-start-12",
      ],
      end: [
        "lg:col-end-auto",
        "lg:col-end-1",
        "lg:col-end-2",
        "lg:col-end-3",
        "lg:col-end-4",
        "lg:col-end-5",
        "lg:col-end-6",
        "lg:col-end-7",
        "lg:col-end-8",
        "lg:col-end-9",
        "lg:col-end-10",
        "lg:col-end-11",
        "lg:col-end-12",
      ],
      auto: [
        "lg:auto-cols-auto",
        "lg:auto-cols-min",
        "lg:auto-cols-max",
        "lg:auto-cols-fr",
      ],
    },
    row: {
      span: [
        "lg:row-auto",
        "lg:row-span-full",
        "lg:row-span-1",
        "lg:row-span-2",
        "lg:row-span-3",
        "lg:row-span-4",
        "lg:row-span-5",
        "lg:row-span-6",
        "lg:row-span-7",
        "lg:row-span-8",
        "lg:row-span-9",
        "lg:row-span-10",
        "lg:row-span-11",
        "lg:row-span-12",
      ],
      start: [
        "lg:row-start-auto",
        "lg:row-start-1",
        "lg:row-start-2",
        "lg:row-start-3",
        "lg:row-start-4",
        "lg:row-start-5",
        "lg:row-start-6",
        "lg:row-start-7",
        "lg:row-start-8",
        "lg:row-start-9",
        "lg:row-start-10",
        "lg:row-start-11",
        "lg:row-start-12",
      ],
      end: [
        "lg:row-end-auto",
        "lg:row-end-1",
        "lg:row-end-2",
        "lg:row-end-3",
        "lg:row-end-4",
        "lg:row-end-5",
        "lg:row-end-6",
        "lg:row-end-7",
        "lg:row-end-8",
        "lg:row-end-9",
        "lg:row-end-10",
        "lg:row-end-11",
        "lg:row-end-12",
      ],
      auto: [
        "lg:auto-rows-auto",
        "lg:auto-rows-min",
        "lg:auto-rows-max",
        "lg:auto-rows-fr",
      ],
    },
  },
};
