export const variants = {
  base: {
    size: [
      "text-xs",
      "text-sm",
      "text-base",
      "text-lg",
      "text-xl",
      "text-2xl",
      "text-3xl",
      "text-4xl",
      "text-5xl",
      "text-6xl",
    ],
    weight: [
      "font-thin",
      "font-extralight",
      "font-light",
      "font-normal",
      "font-medium",
      "font-semibold",
      "font-bold",
      "font-extrabold",
      "font-black",
    ],
  },
  medium: {
    size: [
      "md:text-xs",
      "md:text-sm",
      "md:text-base",
      "md:text-lg",
      "md:text-xl",
      "md:text-2xl",
      "md:text-3xl",
      "md:text-4xl",
      "md:text-5xl",
      "md:text-6xl",
    ],
  },
  large: {
    size: [
      "lg:text-xs",
      "lg:text-sm",
      "lg:text-base",
      "lg:text-lg",
      "lg:text-xl",
      "lg:text-2xl",
      "lg:text-3xl",
      "lg:text-4xl",
      "lg:text-5xl",
      "lg:text-6xl",
    ],
  },
};
